name: PR checks

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'LICENSE'
      - 'getting_started.md'
      - 'docker-compose.yml'
      - 'playground/**'
      - 'CNAME'
      - 'requirements.txt'

env:
  go-version: '1.23.2'
  golangci-lint-version: v1.60

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: 
      - tests

  code_check:
    name: lint
    runs-on: ubuntu-latest
    needs: 
      - tests
    steps:
      - uses: actions/checkout@v4      
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}

      - uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: coverage.out
          key: ${{ runner.os }}-coverage-${{ github.sha }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.golangci-lint-version }}

      - name: echo
        run: echo coverage.out

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.projectKey=tarbaev-vl_greenmask
            -Dsonar.organization=tarbaev-vl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}