name: Deploy development documentation (from main branch)

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/**'

env:
  python-version: 'pypy3.10'

jobs:
  docs:
    uses: ${{ github.repository }}/.github/workflows/docs.yml@main
    needs: 
      - build
    with:
      python-version: ${{ env.python-version }}
